# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjXaSXaO2fs6KM3iOCOO6KyjT96CCsVs
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest

df = pd.read_csv("/content/cricket scoredataset.csv")
df.head(20)

df.head(20)

model = IsolationForest(n_estimators=1000,max_samples='auto',contamination=float(0.2),max_features=1.0)

model.fit(df[["Score"]])

df['Score'] = model.decision_function(df[["Score"]])

df['anomaly'] = model.predict(df[["Score"]])
df.head(20)

outliers_counter = len(df[df['Score'] > 36])

outliers_counter

import matplotlib.pyplot as plt

plt.scatter(df['Score'],df["Overs"])

df.shape

df.head(21)

