# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOVqEpspWS0QzF_E9xFj8H5lVt8dMZMW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/student_clustering.csv")

df.head()

plt.scatter(df["cgpa"],df["iq"])

from sklearn.cluster import KMeans

njr = []

for i in range(1,11):
  km = KMeans(n_clusters = i)
  km.fit_predict(df)
  njr.append(km.inertia_)

njr

plt.plot(range(1,11),njr)

x = df.iloc[:,:].values

km = KMeans(n_clusters=4)
y_means = km.fit_predict(x)

plt.scatter(x[y_means==0,0],x[y_means==0,1],color="blue")
plt.scatter(x[y_means==1,0],x[y_means==1,1],color="green")
plt.scatter(x[y_means==2,0],x[y_means==2,1],color="red")
plt.scatter(x[y_means==3,0],x[y_means==3,1],color="yellow")

