# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vi2py2jo2k_I--kamRk6XITBaoSI2IY8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/iris_csv.csv")
df.head()

x = df.iloc[:,:-1]

y = df.iloc[:,4]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

sc.fit(x_train)

from sklearn.neighbors import KNeighborsClassifier

cs = KNeighborsClassifier(n_neighbors = 3)
cs.fit(x_train,y_train)

y_pred = cs.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

from sklearn.linear_model import LogisticRegression