# -*- coding: utf-8 -*-
"""Naive Credit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18g5AUtfZ9ngvfnoUozd4m1jzP-vVJ-hU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import gridspec

df=pd.read_csv("/content/creditcard.csv")
df.head()

fraud=df[df["Class"]==1]
valid=df[df["Class"]==0]
outlierfrac=len(fraud)/float (len(valid))
print(len(fraud))

correl=df.corr()

sns.heatmap(correl,vmax=10,square=True)

x=df.drop(['Class'],axis=1)
y=df['Class']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)

from sklearn.naive_bayes import GaussianNB

gb=GaussianNB()

gb.fit(x_train,y_train)

pred=gb.predict(x_train)

from sklearn.metrics import classification_report

print(classification_report(y_train,pred))

