# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10v5sH4vwoZnNjZf6G0YWWyGOn6xCWLSV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Social_Network_Ads.csv")

df.head()

x = df.iloc[:,2:4]

y = df.iloc[:,4]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)

x_test = sc.transform(x_test)

from sklearn.svm import SVC

classifier = SVC(kernel="linear",random_state=0)

classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

classifier = SVC(kernel = "linear",random_state=0)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
plt.scatter(x_test[:,0],x_test[:,1],c=y_test)
w = classifier.coef_[0]
a = -w[0]/w[1]
xx = np.linspace(-2.5,2.5)
yy = a*xx-(classifier.intercept_[0]/w[1])
plt.plot(xx,yy)
plt.show()

